logging:
  level:
    ROOT: DEBUG

spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/postgres
    username: ermct
    password: ermct00
    hikari:
      maximum-pool-size: 1

server:
  port: 11111

mybatis:
#  mapper-locations: file:D:/05.IntelliJ/MybatisRest/mapper/**/*.xml
  mapper-locations: classpath:/mapper/**/*.xml
  configuration:
    call-setters-on-nulls: true